apiVersion: v1
kind: Service
metadata:
  name: pubsub
spec:
  selector:
    app.kubernetes.io/name: pubsub
  ports:
    # クライアント慣習のポート 8085 を Google Cloud Pub/Sub エミュレーターの待受ポート 8681 に転送する
    - port: 8085
      targetPort: 8681
