apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# バージョンを上げる場合は下記 URL の <tag> 部分を新しいタグに書き換える
namespace: argocd
resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.4.4/manifests/install.yaml
